Fix linting issues
ridafkih/schemix pull request #31
Opened 2022-09-30 11:55 UTC by zygopleural

I noticed that there were some linting issues: 
```shell
33 problems (33 errors, 0 warnings)
26 errors and 0 warnings potentially fixable with the `--fix` option.
```

So I have enabled checking and fixing those in the `package.json`.

I have ignored the `example` dir as I was seeing
```shell
The file does not match your project config: example/enums/Status.enum.ts.
The file must be included in at least one of the projects provided
```

I would suggest adding a pre-commit hook and / or a GHA CI workflow to check linting on PRs.

2022-09-30 18:36 UTC, ridafkih requested changes
Conflicts! 🕺

2022-09-30 19:28 UTC, zygopleural commented
> Conflicts! 🕺

On it

2022-09-30 19:32 UTC, zygopleural commented
> > Conflicts! 🕺
> 
> On it

Done

2022-09-30 19:32 UTC, zygopleural commented on .eslintrc
> -  "files": ["*.ts"],
This is actually not a valid config option. Dunno why I originally added it.

2022-10-02 01:52 UTC, ridafkih approved these changes

2022-10-02 01:52 UTC, merged